### ISSUE TITLE
Fix: Update Node Info

### ISSUE THREAD

**Issue by lzpap** [iotaledger/iota.lib.js#847]
## Goal
Refactor info response from core api.
`alpha9` will have some changes in the client API:

- Make sure all routes and responses are up to date with [TIP-25](https://github.com/iotaledger/tips/pull/57)

## Background
We have added milestoneId fields in the info response, restructured latestMilestone and ConfirmedMilestone:

```yaml
    InfoResponse:
      description: Returns general information about the node.
      properties:
        name:
          type: string
          description: The name of the node.
        version:
          type: string
          description: The semantic version of the node.
        status:
          description: Status of the node.
          properties:
            isHealthy:
              type: boolean
              description: Tells whether the node is healthy or not.
            latestMilestone:
              type: object
              description: Information about the latest seen milestone.
              properties:
                index:
                  type: integer
                  description: The index of the latest seen milestone.
                timestamp:
                  type: integer
                  description: The timestamp of the latest seen milestone.
                milestoneId:
                  type: string
                  description: The Milestone ID of the latest seen milestone. Hex-encoded with 0x prefix.
              required:
                - index
                - timestamp
                - milestoneId
            confirmedMilestone:
              type: object
              description: Information about the latest confirmed milestone.
              properties:
                index:
                  type: integer
                  description: The index of the latest confirmed milestone.
                timestamp:
                  type: integer
                  description: The timestamp of the latest confirmed milestone.
                milestoneId:
                  type: string
                  description: The Milestone ID of the latest confirmed milestone. Hex-encoded with 0x prefix.
              required:
                - index
                - timestamp
                - milestoneId
```
